name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r client/requirements.txt
          pip install -r server/requirements.txt
          pip install flake8 pytest
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint shell scripts
        run: |
          shellcheck $(git ls-files '*.sh')
      - name: Run flake8
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          flake8 client server scripts tests
      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q
